### ISSUE TITLE
Old GUI version

### ISSUE THREAD

**Issue by R2rino** [MoshiMoshi0/TTController#22]
Hello! Could you please provide a link with the old GUI version of your program? (v1.7) The one on the first page doesn't seems to work anymore. Thank you!

**Comment by MoshiMoshi0** [comment]
Seems to be working fine for me. 
But here: [RiingPlusController_v1.7.zip](https://github.com/MoshiMoshi0/TTController/files/3398830/RiingPlusController_v1.7.zip)
