### ISSUE TITLE
Failed to start the service

### ISSUE THREAD

**Issue by mchnb003** [MoshiMoshi0/TTController#25]
### Prerequisites

> Replace `[ ]` to `[x]` to check

* [x] The controller is recognized without issues in the official software
* [x] I made sure no official software or any other software that can communicate with the controllers (e.g. Aida64) was running when the issue with the service occurred

**Describe the issue**
when i try to start the service, i receive a timeout, se attachements.
Can you please help me, to figure out what i am doing wrong ?
Thx a lot and best regards from munich
Boris

[current.log](https://github.com/MoshiMoshi0/TTController/files/3563445/current.log)
![Error Screenshot](https://user-images.githubusercontent.com/54280492/64076269-f6ed9d80-ccc2-11e9-92e2-cde34d609bfc.PNG)

**Comment by MoshiMoshi0** [comment]
If you use the windows unzip functionality you have to first right click the zip archive, click properties, and click "Unblock" button. But I would recommend using winrar or 7zip.

You can also use the latest [dev build](https://ci.appveyor.com/project/MoshiMoshi0/ttcontroller/build/artifacts) which has a builtin solution for that problem.

**Comment by mchnb003** [comment]
Perfect, ti used 7Zip now, reinstalled the service and it's on :-)
Thank you very much !
