### ISSUE TITLE
No TTController.service.exe

### ISSUE THREAD

**Issue by Ijustwantthemtowork** [MoshiMoshi0/TTController#42]
I tried to install, following the docs given; but after searching manually and through Explorer, the file you called "TTController.service.exe" is not anywhere in the files, even after re-download. There is a TTController.sln, but this just opens the project. Any idea what the issue is?

**Comment by MoshiMoshi0** [comment]
You downloaded the source code not a released build.
All releases are on the "[releases](https://github.com/MoshiMoshi0/TTController/releases)" tab.
