### ISSUE TITLE
Help Installing

### ISSUE THREAD

**Issue by admawby** [MoshiMoshi0/TTController#43]
**Describe the issue**
First of all, thank you all for working on this! Sorry if this is a dumb question, but i don't see any EXE files to install the service as described in the docs. Am I to understand that i should build it myself? I tried building with visual studio but it failed with a bunch of errors, most of which were citing failure to find files in the Third Party folder. Any guidance would be appreciated!

**Debug report**
```
N/A?
```

**Current configuration**
```json
N/A?
```

**Comment by MoshiMoshi0** [comment]
You downloaded the source code not a released build.
All releases are on the "[releases](https://github.com/MoshiMoshi0/TTController/releases)" tab.

Github makes it pretty confusing.

**Comment by admawby** [comment]
*facepalm*

thank you
