### ISSUE TITLE
Thermaltake Pure Plus 14 software wont detect controller

### ISSUE THREAD

**Issue by durand19** [MoshiMoshi0/TTController#55]
My Pure Plus 14s aren't detected by the software. What should i do?

**Comment by MoshiMoshi0** [comment]
Are they detected by the official software?

**Comment by durand19** [comment]
What is the official software? I've been trying with the TT RGB Plus one till now.

Also, my controller is the one with the 3 buttons on it.... don't know if that gives you extra information or not

**Comment by MoshiMoshi0** [comment]
Yes, TT RGB Plus is the official software from thermaltake.
If your controller does not have usb connection then no software will be able to control it.

**Comment by durand19** [comment]
I bought the wrong product.... bought the regular Pure instead of the Pure Plus.... Sorry for wasting your time :/
