### ISSUE TITLE
TT Toughram RGB support

### ISSUE THREAD

**Issue by cwills75** [MoshiMoshi0/TTController#82]
**Describe the feature you'd like**
Is there any way Thermaltake's RAM RGB lighting could be controlled and/or synced with TTController?  I have four sticks of TOUGHRAM RGB.  Currently, I'm using G.Skill's Trident Z Lighting Control software since it allows me to set a color/effect that persists even when the software closes.  Thermaltake's own software defaults back to rainbow upon closing and introduces lag into my system.  The memory sticks also work with my motherboard's (Gigabyte) RGB Fusion software, but it is very limited.  Ideally, if it could be controlled via TTController and synced with another control profile if desired, that would be the best-case scenario.

**Comment by MoshiMoshi0** [comment]
Currently there is no way to do this in TTController. It requires access to smbus and C# is not designed for such low level stuff.

I might figure something out from thermaltake software but testing this will be very tricky since I dont have any RGB ram myself. This needs access to the motherboard itself so you can easily cause bluescreens or other bad stuff, and i would not want to break something on your pc.

**Comment by cwills75** [comment]
OK, no problem.  Thanks for responding.

**Comment by MoshiMoshi0** [comment]
I'll leave this issue open for now as a feature request. I'll see what can be done.

**Comment by cwills75** [comment]
OK, If you work on things and want me to test it, let me know.

**Comment by MoshiMoshi0** [comment]
Unfortunately I think this wont be added to TTController.

It will be very wonky to do in C#, if its even possible, and it does not fit the current code architecture so it would require a substantial rewrite/refactoring.

I think the best solution here would be to write a separate C++ application that reads the led colors of the fans from TTController via websocket and maps them to specific ram stick. But that would be the same as using any other software that can change ram rgb, other than syncing with thermaltake fan leds.

I'll keep this app in mind as I do plan to write a few simple apps that connect to the TTController websocket but I dont know when or if I'll manage to write one.
